/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem */

#ifndef _Included_au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem
#define _Included_au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_MIN_PRIORITY
#define au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_MIN_PRIORITY 1L
#undef au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_NORM_PRIORITY
#define au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_NORM_PRIORITY 5L
#undef au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_MAX_PRIORITY
#define au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_MAX_PRIORITY 10L
/*
 * Class:     au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_register
  (JNIEnv *, jobject);

/*
 * Class:     au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem
 * Method:    sendSystex
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_au_com_pwcu_nanopad2controller_midisystem_NanoPad2MidiSystem_sendSystex
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
